# Generated by Django 3.0.4 on 2020-04-08 14:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyHome',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='beds',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='dementia_beds',
        ),
        migrations.RemoveField(
            model_name='home',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='home',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='home',
            name='local_authority',
        ),
        migrations.RemoveField(
            model_name='home',
            name='no_beds',
        ),
        migrations.RemoveField(
            model_name='home',
            name='provider',
        ),
        migrations.AddField(
            model_name='bed',
            name='nus_beds',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='nus_dem_beds',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='res_beds',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='res_dem_beds',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='vacancy_updated',
            field=models.DateField(verbose_name=datetime.datetime(2020, 4, 8, 14, 38, 22, 737708, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
