# Generated by Django 3.0.4 on 2020-04-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0003_auto_20200409_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='vacancy_updated',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
