# Generated by Django 3.0.4 on 2020-04-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0004_auto_20200409_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='vacancy_updated',
        ),
    ]
