# Generated by Django 3.0.4 on 2020-04-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0005_remove_home_vacancy_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='vacant_beds',
            field=models.IntegerField(null=True),
        ),
    ]
