# Generated by Django 3.0.4 on 2020-04-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0006_auto_20200409_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='page_number',
            field=models.IntegerField(default=0),
        ),
    ]
